[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
  'numpy',
  'networkx',
  'ninja'
]
name = "orbit-count"
requires-python = ">=3.7"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    'pytest',
    'memory_profiler'
]